echo $BASH
echo $BASH_VERSION
echo $HOME
echo $PWD
echo $USER
echo $UID
echo $SHELL
echo $OSTYPE
echo $MACHTYPE
echo $HOSTNAME
echo $HOSTTYPE
echo $MACHTYPE
echo $PATH
echo $EDITOR
echo $LANG
echo $LC_ALL
echo $LC_COLLATE
echo $LC_CTYPE
echo $LC_MESSAGES
echo $LC_MONETARY
echo $LC_NUMERIC
echo $LC_TIME
echo $TERM
echo $TERM_PROGRAM
echo $TERM_PROGRAM_VERSION
echo $TERM_SESSION_ID
echo $TMPDIR
echo $USER
echo $XPC_FLAGS
echo $XPC_SERVICE_NAME
echo $SHLVL
echo $HOME
echo $LOGNAME
